import { Competencia } from "../models/Competencia";

export const instanciarCompetencias = (): Competencia[] => {

  const competencias = [new Competencia({ nome: 'HTML' })
    , new Competencia({ nome: 'CSS' })
    , new Competencia({ nome: 'JavaScript' })
    , new Competencia({ nome: 'React' })
    , new Competencia({ nome: 'Node.js' })
    , new Competencia({ nome: 'Python' })
    , new Competencia({ nome: 'Java' })
    , new Competencia({ nome: 'Ruby' })
    , new Competencia({ nome: 'C#' })
    , new Competencia({ nome: 'PHP' })
    , new Competencia({ nome: 'Swift' })
    , new Competencia({ nome: 'Kotlin' })
    , new Competencia({ nome: 'Angular' })
    , new Competencia({ nome: 'Vue.js' })
    , new Competencia({ nome: 'Express.js' })
    , new Competencia({ nome: 'Django' })
    , new Competencia({ nome: 'Spring Boot' })
    , new Competencia({ nome: 'Ruby on Rails' })
    , new Competencia({ nome: 'Unity' })
    , new Competencia({ nome: 'Machine Learning' })
    , new Competencia({ nome: 'Data Science' })
    , new Competencia({ nome: 'DevOps' })
    , new Competencia({ nome: 'Cybersecurity' })
    , new Competencia({ nome: 'UI/UX Design' })
    , new Competencia({ nome: 'Digital Marketing' })
    , new Competencia({ nome: 'Content Writing' })
    , new Competencia({ nome: 'Project Management' })
    , new Competencia({ nome: 'Product Management' })
    , new Competencia({ nome: 'Agile Methodology' })
    , new Competencia({ nome: 'Scrum' })
    , new Competencia({ nome: 'Kubernetes' })
    , new Competencia({ nome: 'AWS' })
    , new Competencia({ nome: 'Azure' })
    , new Competencia({ nome: 'Google Cloud' })
    , new Competencia({ nome: 'Blockchain' })
    , new Competencia({ nome: 'AR/VR Development' })
    , new Competencia({ nome: 'Mobile App Development' })
    , new Competencia({ nome: 'Web Development' })
    , new Competencia({ nome: 'Database Management' })
    , new Competencia({ nome: 'Front-End Development' })
    , new Competencia({ nome: 'Back-End Development' })
    , new Competencia({ nome: 'Full-Stack Development' })
    , new Competencia({ nome: 'Cloud Computing' })
    , new Competencia({ nome: 'Big Data' })
    , new Competencia({ nome: 'Artificial Intelligence' })
    , new Competencia({ nome: 'Natural Language Processing' })
    , new Competencia({ nome: 'Computer Vision' })
    , new Competencia({ nome: 'Quantum Computing' })
    , new Competencia({ nome: 'Internet of Things (IoT)' })
    , new Competencia({ nome: 'Blockchain Development' })
    , new Competencia({ nome: 'Game Development' })
    , new Competencia({ nome: 'UI/UX Research' })
    , new Competencia({ nome: 'Product Design' })
    , new Competencia({ nome: 'Agile Coaching' })
    , new Competencia({ nome: 'Business Analysis' })
    , new Competencia({ nome: 'Sales' })
    , new Competencia({ nome: 'Customer Service' })
    , new Competencia({ nome: 'Human Resources' })
  ];

  return competencias;
};
